In [2]:
import pandas as pd
import numpy as np
import cPickle as pickle
import matplotlib.pyplot as plt

In [3]:
with open('../data/review_dataframe3.pkl', 'r') as f:
    review0_df = pickle.load(f)

In [4]:
review0_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35433 entries, 580690 to 1143461
Data columns (total 4 columns):
business_id_int    35433 non-null int64
review_date        35433 non-null object
review_stars       35433 non-null int64
user_id_int        35433 non-null int64
dtypes: int64(3), object(1)
memory usage: 1.4+ MB


In [9]:
reviews = review0_df[['user_id_int', 'business_id_int', 'review_stars']]

In [10]:
reviews.user_id_int.nunique()

6492

In [11]:
reviews.business_id_int.nunique()

3848

In [1]:
from scipy.sparse import csr_matrix, dok_matrix, lil_matrix, coo_matrix

In [38]:
csr = csr_matrix([[1,2,0],[0,0,3],[4,0,5]])
dok = dok_matrix([[1,2,0],[0,0,3],[4,0,5]])
lil = lil_matrix([[1,2,0],[0,0,3],[4,0,5]])
coo = coo_matrix([[1,2,0],[0,0,3],[4,0,5]])

In [36]:
coo.nonzero()

(array([0, 0, 0, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 2, 0, 2], dtype=int32))

In [40]:
coo[0,2] = 6

TypeError: 'coo_matrix' object does not support item assignment

In [44]:
dok.tocsr()

<3x3 sparse matrix of type '<type 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [54]:
a = lil!= 0

In [55]:
print a

  (0, 0)	True
  (0, 1)	True
  (1, 2)	True
  (2, 0)	True
  (2, 2)	True


In [56]:
print lil

  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5


In [61]:
print lil[a][0]

  (0, 0)	1
  (0, 1)	2
  (0, 2)	3
  (0, 3)	4
  (0, 4)	5


In [64]:
b=dok.tocsc()

In [70]:
print dok

  (0, 1)	2
  (1, 2)	3
  (0, 0)	1
  (2, 0)	4
  (2, 2)	5


In [67]:
b[0,1]=3

In [69]:
print b

  (0, 0)	1
  (2, 0)	4
  (0, 1)	3
  (1, 2)	3
  (2, 2)	5


In [98]:
print coo.col

[0 1 2 0 2]


In [75]:
print coo

  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5


In [108]:
coo.col == 2

array([False, False,  True, False,  True], dtype=bool)

In [102]:
print np.array(c.sum(axis=0)).reshape(-1)

[2 1 2]


In [104]:
print c

  (0, 0)	True
  (0, 1)	True
  (1, 2)	True
  (2, 0)	True
  (2, 2)	True


In [112]:
A = np.array([1,2,3,4,1,2,3,4,1,2,3,4])

In [120]:
A[np.where(A==4)[0]].mean()

4.0

In [122]:
np.mean([1,2,3,4])

2.5

In [124]:
19413 / 5270 / 3809. * 100

0.07876082961407194

In [6]:
positions = pd.read_csv('../fig/positions', sep=' ',  names=['x', 'y', 'city'], header=None)

In [8]:
plt.scatter(positions.x, positions.y, c=positions.city)

In [9]:
plt.show()